region: us-east-1

function_name: ita_trade_events
handler: service.handler
role: lambda_api
description: Fetches trade events, builds a single JSON document, and stores it in S3
runtime: python3.8

timeout: 300
memory_size: 128
